services:

  db:
    image: postgres:15.6-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME?Variable not set}.app-db-data == true

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_LISTEN_PORT: 80
    env_file:
      - .env
    ports:
      - 5050:80

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build:
      dockerfile: backend.dockerfile
      args:
        ENV_CONFIG: ${ENV_CONFIG-dev}
    env_file:
      - .env
    volumes:
      - app-file-storage:/app/files
    environment:
      - ENV_CONFIG=${ENV_CONFIG-dev}
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    ports:
      - 80:80

volumes:
  app-db-data:
  app-file-storage:
