"""update: add customer column

Revision ID: 7f7e8565794e
Revises: c6e204861848
Create Date: 2024-05-27 07:03:01.728273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7e8565794e'
down_revision = 'c6e204861848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('customer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'customer')
    # ### end Alembic commands ###
