"""update: add country column

Revision ID: c6e204861848
Revises: ea67a970b841
Create Date: 2024-05-09 13:00:43.586899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e204861848'
down_revision = 'ea67a970b841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'country')
    # ### end Alembic commands ###
