"""add station table

Revision ID: ea67a970b841
Revises: f92f11243217
Create Date: 2024-05-09 12:55:04.168640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea67a970b841'
down_revision = 'f92f11243217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('coordinates', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('geo_region', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_id'), 'station', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_id'), table_name='station')
    op.drop_table('station')
    # ### end Alembic commands ###
